# Copyright 2026 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



- name: Ensure inventory readiness
  hosts: all
  gather_facts: false
  tags:
    - readiness
  tasks:
    - name: Check if host is ready
      ansible.builtin.wait_for_connection:
        timeout: 60


- name: Create TLS Certificates for FreeIPA Enrolled host
  hosts: postgresql
  gather_facts: true
  become: true
  vars:
    enrolled_hostname: "{{ inventory_hostname }}"
    ipaadmin_password: "{{ common_password }}"
    keystore_path: /etc/pki/tls/private/keystore.jks
    truststore_path: /etc/pki/tls/private/truststore.jks
  roles:
    - cloudera.exe.freeipa_server_enrolled_tls

- name: Create TLS Keystores for EFM-MINIFI
  hosts: postgresql
  gather_facts: yes
  become: yes
  roles:
    - cloudera.exe.tls_keystores
  vars:
    keystore_password: "{{ common_password }}"
    keystore_alias: "service-cert"
    keystore_cert_path: "/etc/pki/tls/certs/host.crt"
    keystore_key_path: "/etc/pki/tls/private/host.key"
    truststore_alias: "ipa-ca"
    ca_cert_path: "/etc/ipa/ca.crt"

- name: Prerequisites for EFM
  hosts: postgresql
  gather_facts: yes
  become: yes
  roles:
    - cloudera.exe.prereq_efm
    - cloudera.exe.prereq_efm_database
  vars:
    database_type: "postgresql"
    database_host: "localhost"
    efm_username: "efm"
    efm_database: "efm"
    efm_password: "{{ common_password}}"


- name: Provision EFM service
  hosts: postgresql
  gather_facts: true
  become: true
  tags: database
  vars:
    efm_repo_username: "{{ lookup('cloudera.cluster.cm_license', cm_license_path).uuid }}"
    efm_repo_password: "{{ lookup('cloudera.cluster.cm_license', cm_license_path).password }}"
    cm_license_path: "{{ lookup('env', 'CDP_LICENSE_FILE')}}"
    efm_encryption_password: "{{ common_password }}"
    efm_db_password: "{{ common_password }}"
    # TLS Configuration
    efm_tls_enabled: true
    efm_ssl_client_auth: "WANT"
    efm_ssl_keystore_type: "jks"
    efm_ssl_truststore_type: "jks"
    efm_ssl_keystore_path: /etc/pki/tls/private/keystore.jks
    efm_ssl_truststore_path: /etc/pki/tls/private/truststore.jks
    efm_ssl_keystore_password: "{{ common_password }}"
    efm_ssl_key_password: "{{ common_password }}"
    efm_ssl_truststore_password: "{{ common_password }}"
    # LDAP Configuration
    efm_ldap_enabled: true
    efm_ldap_url: "ldaps://{{ groups['freeipa'] | first }}:636"
    efm_ldap_authentication_strategy: "LDAPS"
    efm_ldap_user_auth_groups_manager: "LDAP"
    efm_ldap_auth_enabled: true
    efm_ldap_auth_search_filter: "(uid={0})"
    efm_ldap_user_search_base: "cn=users,cn=accounts,dc=cldr,dc=internal"
    efm_ldap_user_object_class: "person"
    efm_ldap_tls_protocol: "TLSv1.2"
    efm_ldap_user_search_scope: "ONE_LEVEL"
    efm_ldap_user_identity_attribute: "uid"
  roles:
    - cloudera.exe.efm



- name: Provision MINIFI CPP Agent
  hosts: postgresql
  gather_facts: true
  become: true
  vars:
    cm_license_path: "{{ lookup('env', 'CDP_LICENSE_FILE')}}"
    minifi_cpp_repo_username: "{{ lookup('cloudera.cluster.cm_license', cm_license_path).uuid }}"
    minifi_cpp_repo_password: "{{ lookup('cloudera.cluster.cm_license', cm_license_path).password }}"
    efm_host_url: "https://{{ groups['postgresql'][0] }}:10090"
    minifi_cpp_agent_class_name: "minifi-cpp-agent"
    minifi_tls_enabled: true
  roles:
    - cloudera.exe.minifi_agent_cpp


- name: Add efm reverse proxy service
  hosts: reverse_proxy
  gather_facts: true
  become: true
  tags:
    - reverse_proxy
    - proxy
  vars:
    tf_inventory: "{{ playbook_dir }}/../tf_cluster_aws"
    external_subdomain: "{{ lookup('cloud.terraform.tf_output', 'gateways', project_path=tf_inventory) | map(attribute='public_ip') | first }}"
  handlers:
    - name: Reload Caddy
      ansible.builtin.service:
        name: caddy
        state: restarted
  tasks:
    - name: Install efm reverse proxy
      ansible.builtin.template:
        src: efm.caddyfile.j2
        dest: /etc/caddy/Caddyfile.d/efm.caddyfile
        mode: "0644"
      vars:
        external_domain: "efm.{{ external_subdomain }}.{{ public_domain }}"
        efm_fqdn: "{{ groups['freeipa'] | first }}:10090"
      notify: Reload Caddy

    - name: Display EFM URL
      ansible.builtin.debug:
        msg: "EFM UI: https://efm.{{ external_subdomain }}.{{ public_domain }}/efm/ui/"


- name: Add EFM link to Endpoints table
  hosts: localhost
  gather_facts: false
  vars:
    tf_inventory: "{{ playbook_dir }}/../tf_cluster_aws"
    external_subdomain: "{{ lookup('cloud.terraform.tf_output', 'gateways', project_path=tf_inventory) | map(attribute='public_ip') | first }}"
  tasks:
    - name: Append EFM link to Endpoints table
      ansible.builtin.replace:
        path: "{{ name_prefix }}-summary.html"
        regexp: "(<h2>Endpoints</h2>\n    <table>\n      <tbody>)"
        replace: |
          \1
          <tr>
            <td scope="col">EFM</td>
            <td><a target="_blank" href="https://efm.{{ external_subdomain }}.{{ public_domain }}/efm/ui/">efm.{{ external_subdomain }}.{{ public_domain }}/efm/ui/</a></td>
          </tr>
